%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
  port-groups:
    HTTP_PORTS: "80,8080,8000,443"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: 1521
    SSH_PORTS: 22

default-log-dir: /var/log/suricata

stats:
  enabled: no

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      community-id: yes
      types:
        - alert:
            payload: yes
            payload-printable: yes
            packet: yes
            metadata: yes
            tagged-packets: yes
        - anomaly

af-packet:
  - interface: enp1s0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    tpacket-v3: yes

pcap:
  - interface: enp1s0

detect:
  profile: medium

rule-files:
  - /var/lib/suricata/rules/suricata.rules
